### PR TITLE
chore(deps): Update haproxy-alpine to 2.4.17

### LINKED ISSUE #217: haproxy-alpine image is outdated and contains vulnerabilities
Hello there! :wave: 

The default tag in `values.yml` is outdated (last pushed 9 months ago) and now contains vulnerabilities.

It can be easily solved by upgrading to the latest patch of the same minor version.

See results from trivy:

```
haproxytech/haproxy-alpine:2.4.4 (alpine 3.12.8)
================================================
Total: 24 (HIGH: 22, CRITICAL: 2)
```

```
haproxytech/haproxy-alpine:2.4.17 (alpine 3.15.4)
=================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
```

### PR DESCRIPTION
**Pull request by SIPR-octo**
Fixes #217 

See the linked issue for more details

### CODE REVIEW

**Comment by spencergilbert** [comment]
Thanks @SIPR-octo do you mind also bumping the patch version and running `helm-docs` to update the README banner?

**Comment by SIPR-octo** [comment]
@spencergilbert Just did!

Seems like a lot of other changes were not commited, I added them in a separate commit.
I can easily revert them if needed.

**Comment by SIPR-octo** [comment]
I just updated the Chart version to make the CI jobs pass.
Do I need to update the README as well?

Unsure to what extend I need to modify this, I did not find any `CONTRIBUTING.md` file :)

**Comment by spencergilbert** [comment]
> Unsure to what extend I need to modify this, I did not find any `CONTRIBUTING.md` file :)

😅 https://github.com/vectordotdev/helm-charts/issues/204

I've got it - it's normally just been myself making changes so I haven't prioritized a lot of documentation

**Comment by SIPR-octo** [comment]
Just upgraded helm-docs version in CI because it seems you generated the doc with a newer version (tested locally, it works).

I can make 2 separate MR if you wish me to (1 for bumping helm-docs, one for haproxy), just let me know.

**Pull request merged**
