### PR TITLE
fix(vector): add minReadySeconds to StatefulSet and Deployment specs

### PR DESCRIPTION
**Pull request by alexanderldavis**
The chart currently supports `minReadySeconds` for DaemonSet-based deployments of the Vector agent. This PR extends this value to also apply to StatefulSets and Deployment specs.

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Thanks @alexanderldavis . This change makes sense to me!

**Comment by jszwedko** [comment]
@alexanderldavis it looks like there are some CI failures here when you get some time.

**Comment by alexanderldavis** [comment]
@jszwedko I'm struggling to find a good way to pass the linter for older kube versions. `minReadySeconds` was added to Statefulsets in v1.22, but made generally available in v1.25. Do you have a recommendation for how that should be handled?

**Comment by jszwedko** [comment]
@alexanderldavis I was expecting the failing CI checks to block the automerge but apparently they didn't 😓 I opened https://github.com/vectordotdev/helm-charts/pull/371 to revert.

> minReadySeconds was added to Statefulsets in v1.22, but made generally available in v1.25

My assumption would be that we'd only want to template it out for v1.25+ then, but maybe I'm missing something 🤔

**Pull request merged**
