### PR TITLE
feat(vector): Add back additionalLabels

### LINKED ISSUE #110: additionalLabels removed from podMonitor
Prometheus requires that the podMonitor opt-in to the namespace for metrics. This is no longer possible without using commonLabels which applies the label to all resources and adds unnecessary clutter.

### PR DESCRIPTION
**Pull request by sam-mcbr**
Add back the ability to specify additional labels on PodMonitor. Fixes #110

### CODE REVIEW

**Comment by sam-mcbr** [comment]
Generated resource with `additionalLabels: {}`:

```
# Source: vector/templates/podmonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vector-1636656955
  labels:
    helm.sh/chart: vector-0.1.1
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector-1636656955
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/version: "0.17.3-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: vector
      app.kubernetes.io/instance: vector-1636656955
      app.kubernetes.io/component: Aggregator
  namespaceSelector:
    matchNames:
      - namespace
  podMetricsEndpoints:
    - port: prom-exporter
      path: /metrics
```

Generated resource with

```
additionalLabels:
  app.test/label: "testLabel"
```

```
# Source: vector/templates/podmonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vector-1636656936
  labels:
    app.test/label: testLabel
    helm.sh/chart: vector-0.1.1
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector-1636656936
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/version: "0.17.3-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: vector
      app.kubernetes.io/instance: vector-1636656936
      app.kubernetes.io/component: Aggregator
  namespaceSelector:
    matchNames:
      - namespace
  podMetricsEndpoints:
    - port: prom-exporter
      path: /metrics
```

**Review by mehta-ankit — APPROVED** [review]

**Comment by spencergilbert** [comment]
Thanks @sam-mcbr - are you able to regenerate the docs? `helm-docs` run from the project root. If not I can and push the commit.

**Comment by sam-mcbr** [comment]
@spencergilbert Forgot to do that, done 👍

**Review by spencergilbert — APPROVED** [review]

**Review by spencergilbert — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
