### PR TITLE
fix: Bump to Vector 0.21.2

### PR DESCRIPTION
**Pull request by jszwedko**
Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

**Review by StephenWakely — CHANGES_REQUESTED** [review]
Looking at the when we bumped to 0.21.1 we also updated the [changelog]( https://github.com/vectordotdev/helm-charts/pull/202/files). I imagine we would want to do that again here.

**Comment by jszwedko** [comment]
🤔 I did run `./.github/release-changelog.sh` but it didn't result in any updates to the CHANGELOG.

**Review by StephenWakely — APPROVED** [review]

**Comment by jszwedko** [comment]
Aaah, I see, this should have been marked as `fix`.

**Comment by jszwedko** [comment]
Realized my changelog fix didn't get pushed here. I pushed it to develop as 76beadf

**Pull request merged**
