### PR TITLE
chore(deps): Update haproxy to version 2.6.12

### PR DESCRIPTION
**Pull request by AryanaP**

### CODE REVIEW

**Comment by neuronull** [comment]
Hi @AryanaP , thanks for updating this dependency.

I verified this new version works with the e2e tests in vector (https://github.com/vectordotdev/vector/actions/runs/4800532180)

So all this PR needs is to update the chart version, and the docs referencing the haproxy version:

https://github.com/vectordotdev/helm-charts/actions/runs/4765788567/jobs/8538852745?pr=297

https://github.com/vectordotdev/helm-charts/actions/runs/4765788567/jobs/8538851362?pr=297

**Comment by AryanaP** [comment]
Hello, 
I updated the doc, but I am not sure on what is expected of me for the chart version.
Your linter says : 
```
Old chart version: 0.21.1
New chart version: 0.21.1
```

Am I not looking at the right log ?

**Comment by StephenWakely** [comment]
> Hello, I updated the doc, but I am not sure on what is expected of me for the chart version. Your linter says :
> 
> ```
> Old chart version: 0.21.1
> New chart version: 0.21.1
> ```
> 
> Am I not looking at the right log ?

Hi. The chart version needs to be updated here https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/Chart.yaml#L3

Then helm docs (https://github.com/norwoodj/helm-docs) needs to be run to update the docs accordingly.

**Review by neuronull — APPROVED** [review]
Looks good, thanks @AryanaP !

**Pull request merged**
