### PR TITLE
added extraContainers option for vector & haproxy pods

### LINKED ISSUE #224: vector _pod.tpl does not offer extraContainers
Is it possible to add `extraContainers` option in [templates/_pod.tpl](https://github.com/vectordotdev/helm-charts/blob/a4e9b7adcf780928fb0a4f5f989c760f75e53d9d/charts/vector/templates/_pod.tpl) (as well as already [existing](https://github.com/vectordotdev/helm-charts/blob/a4e9b7adcf780928fb0a4f5f989c760f75e53d9d/charts/vector/values.yaml#L268) initContainers field) in ability to deploy custom sidecars with vector pods?

### PR DESCRIPTION
**Pull request by r0b3r4**
extraContainers allows you to run sidecars containers along with the main container

Closes #224

### CODE REVIEW

**Comment by r0b3r4** [comment]
Was tested on k8s cluster with next values:
`extraContainers:
  - name: sleep
    image: busybox
    command: ['sh', '-c', "while true;do sleep 5; done"]

haproxy:
  enabled: true
  extraContainers:
    - name: sleep
      image: busybox
      command:
        - 'sh'
        - '-c'
        - 'while true;do sleep 5; done'
`

**Comment by spencergilbert** [comment]
Thanks for the PR, I bumped the version and did some comment/readme cleanup.

**Comment by r0b3r4** [comment]
We are waiting another one person for approve?

**Review by jszwedko — APPROVED** [review]
Approving since I believe @spencergilbert meant to when enabling auto merge. The changes also look good to me.

**Pull request merged**
