### PR TITLE
feat(vector): Add honorLabels and honorTimestamps to PodMonitor

### LINKED ISSUE #152: Vector PodMonitor honor_label configuration
It would be nice to set honor_labels for the PodMonitor to avoid exported_ labels if you use vector as aggregator for metrics in front of Prometheus.

### PR DESCRIPTION
**Pull request by tarfu**
Add ability to set honorLabels and honorTimestamps for the PodMonitor which can be deployed with the vector helm chart. Fixes #152

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

**Comment by spencergilbert** [comment]
Thanks for the contribution @tarfu - would you mind bumping the version to 0.5 and regenerating the docs with `helm-docs`?

**Comment by tarfu** [comment]
I regenerated the helm-docs, but I don't understand why it doesn't recognize the description.

**Comment by spencergilbert** [comment]
> I regenerated the helm-docs, but I don't understand why it doesn't recognize the description.

🤔 I'll pull the PR locally and see if I can figure it out, it's been a while since I've messed with helm-docs it has "Just Worked"...

**Comment by spencergilbert** [comment]
Thanks for the PR!

**Comment by tarfu** [comment]
Saw it the second you commented -.-

 Thanks for the help!

**Pull request merged**
