### PR TITLE
fix(vector): have psp support hostNetwork: true when podHostNetwork is true

### PR DESCRIPTION
**Pull request by nascd**

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Thanks @nascd !

**Comment by jszwedko** [comment]
I think you just need to bump the chart version.

**Comment by jszwedko** [comment]
(pressed the wrong button 😓 )

**Comment by nascd** [comment]
> I think you just need to bump the chart version.

Thanks @jszwedko, just a patch increment to https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/Chart.yaml#L3 ?  Should I include that in this PR, or a follow-up after this is merged?

**Comment by jszwedko** [comment]
> > I think you just need to bump the chart version.
> 
> Thanks @jszwedko, just a patch increment to https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/Chart.yaml#L3 ? Should I include that in this PR, or a follow-up after this is merged?

Yeah, I think it would just be a patch bump. It'll have to be part of this PR to satisfy the linter 🙏

**Comment by nascd** [comment]
@jszwedko I've bumped the version.  I don't appear to have permissions to merge, but please let me know if there's anything else I need to do.  Thank you!

**Review by jszwedko — APPROVED** [review]
Thanks!

**Comment by nascd** [comment]
Is there something else required to get this chart available in the public repository?

**Comment by jszwedko** [comment]
> Is there something else required to get this chart available in the public repository?

We are planning a release for next week so I think we can just loop it in with that.

**Pull request merged**
